#
# Copyright (c) 2020, 2025, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
security:
  providers:
  - http-basic-auth:
      realm: "weavesocks"
coherence:
  topic:
    enabled: false
  proxy:
    enabled: false
  tracing:
    ratio: -1
otel:
  sdk:
    disabled: false
  service:
    name: Users
  traces:
    exporter: otlp
  logs:
    exporter: otlp
  exporter:
    otlp:
      traces:
        endpoint: http://opentelemetry-kube-stack-deployment-collector.monitoring:4317
      logs:
        endpoint: http://opentelemetry-kube-stack-deployment-collector.monitoring:4317
