#
# Copyright (c) 2020, 2025, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
grpc:
  client:
    channels:
      - name: "default"
        tls:
          enabled: "false"
      - name: "payment"
        host: "payment"
        port: 80
        tls:
          enabled: "false"
        interceptors:
          - com.oracle.coherence.examples.sockshop.helidon.orders.TracePropagationClientInterceptor
      - name: "shipping"
        host: "shipping"
        port: 80
        tls:
          enabled: "false"
        interceptors:
          - com.oracle.coherence.examples.sockshop.helidon.orders.TracePropagationClientInterceptor
grpc-client:
  grpc-services:
    tracing:
      enabled: true
coherence:
  topic:
    enabled: false
  proxy:
    enabled: false
  tracing:
    ratio: -1
otel:  
  service:
    name: Orders
  agent:
    present: true

