#
# Copyright (c) 2020, 2025, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
grpc:
  grpc-services:
    tracing:
      enabled: true
  client:
    channels:
      - name: "default"
        tls:
          enabled: "false"
coherence:
  topic:
    enabled: false
  proxy:
    enabled: false
  tracing:
    ratio: 1.0
otel:  
  service:
    name: Shipping
  agent:
    present: true

