#
# Copyright (c) 2020, 2025, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
grpc:
  server:
    # Enable tracing for gRPC server
    tracing:
      enabled: true
  client:
    channels:
      - name: "default"
        tls:
          enabled: "false"
coherence:
  topic:
    enabled: false
  proxy:
    enabled: false
  tracing:
    ratio: -1
otel:
  sdk:
    disabled: false
  service:
    name: Payment
  traces:
    exporter: otlp
  logs:
    exporter: otlp
  exporter:
    otlp:
      traces:
        endpoint: http://opentelemetry-kube-stack-deployment-collector.monitoring:4317
      logs:
        endpoint: http://opentelemetry-kube-stack-deployment-collector.monitoring:4317
