{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
  labels:
    {{- include "sockshop.service.labels" (dict "name" .Values.frontend.name) | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
  selector:
    {{- include "sockshop.service.selectorLabels" (dict "name" .Values.frontend.name) | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  labels:
    {{- include "sockshop.service.labels" (dict "name" .Values.frontend.name) | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "sockshop.service.selectorLabels" (dict "name" .Values.frontend.name) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sockshop.service.labels" (dict "name" .Values.frontend.name) | nindent 8 }}
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: {{ .Values.frontend.name }}
        image: {{ include "sockshop.image" (dict "global" .Values.global "image" .Values.frontend.image) }}
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: {{ .Values.frontend.env.otelExporterEndpoint | quote }}
        resources:
          {{- toYaml .Values.frontend.resources | nindent 10 }}
        ports:
        - containerPort: {{ .Values.frontend.service.targetPort }}
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        securityContext:
          {{- toYaml .Values.frontend.securityContext | nindent 10 }}
      volumes:
      - name: tmp
        emptyDir: {}
{{- end }}
